# Generated by Django 4.2.6 on 2023-10-13 07:32

from django.db import migrations, models


def rename_siae_staff(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(kind="siae_staff").update(kind="employer")


def revert_rename(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(kind="employer").update(kind="siae_staff")


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_jobseekerprofile_birth_country_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="has_kind",
        ),
        migrations.AlterField(
            model_name="user",
            name="kind",
            field=models.CharField(
                choices=[
                    ("job_seeker", "candidat"),
                    ("prescriber", "prescripteur"),
                    ("employer", "employeur"),
                    ("labor_inspector", "inspecteur du travail"),
                    ("itou_staff", "administrateur"),
                ],
                max_length=20,
                verbose_name="type",
            ),
        ),
        migrations.RunPython(rename_siae_staff, reverse_code=revert_rename),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("kind", "itou_staff"),
                    ("kind", "job_seeker"),
                    ("kind", "prescriber"),
                    ("kind", "employer"),
                    ("kind", "labor_inspector"),
                    _connector="OR",
                ),
                name="has_kind",
                violation_error_message="Le type dâ€™utilisateur est incorrect.",
            ),
        ),
    ]
